### ISSUE TITLE
Pi4 to ESP32 to TBS Fusion

### ISSUE THREAD

**Issue by peacemosquitto** [BrainFPV/tbs-fusion-py#2]
I'm trying to connect via serial to the TBS fusion using an ESP32 to create a half duplex connection the fusion module and then use the esp32 as a passthrough to my Pi4. Do you have an example hardware laydown of how would be best to achieve this as I keep getting 'No Data Received' or 'Sync bytes invalid'.

**Comment by peacemosquitto** [comment]
When I hook up the logic analyser I can see my transmitted message, and when setting the frequency this works but I don't get any response from the fusion.

**Comment by peacemosquitto** [comment]
<img width="1427" alt="Screenshot 2024-05-09 at 2 35 44 PM" src="https://github.com/BrainFPV/tbs-fusion-py/assets/169354174/c2008338-b9f7-4945-9dac-87b86226d17f">

**Comment by peacemosquitto** [comment]
Looking at the analogue there's definitely a small signal coming back but not enough to register. Possible hardware fault? I'm currently powering the fusion from a dedicated power supply module so current draw shouldn't be an issue.
<img width="1427" alt="Screenshot 2024-05-09 at 3 27 03 PM" src="https://github.com/BrainFPV/tbs-fusion-py/assets/169354174/b50a4268-192f-469f-9d0a-356ba8bdc999">

**Comment by mluessi** [comment]
@peacemosquitto please share the schematic that shows how it is connected to the ESP32. If the ESP32 doesn't support half-duplex, it needs a circuit with two FETs as shown in the [documentation](https://www.team-blacksheep.com/media/files/tbs-fusion-serial-interface.pdf)

**Comment by peacemosquitto** [comment]
This is just the signal coming from the RXTX pinout when I transmit to it. If the logic analyzer is unable to recongize the return signal then the ESP32 can't either. The ESP32 supports half duplex using SoftwareSerial.

**Comment by mluessi** [comment]
@peacemosquitto the fusion has a 10k Ohm series resistor on the TXRX pin, so if the ESP32 doesn't switch the pin to input immediately after sending the data, the fusion won't be able to pull the signal low. You may need to use full duplex and the external circuit to make it half duplex.

**Comment by peacemosquitto** [comment]
Thank you, that's cleared that up. Are you able to recommend hardware that can connect via full duplex to the TBS Fusion?

**Comment by mluessi** [comment]
@peacemosquitto I'm not sure if I understand the question. The fusion itself is half duplex, so you need a half duplex hardware to connect to it.

**Comment by peacemosquitto** [comment]
Apologies my mistake, are you able to recommend some half duplex capable hardware?

**Comment by antoxi4** [comment]
> Apologies my mistake, are you able to recommend some half duplex capable hardware?

Hi @peacemosquitto , did you figure it out with that problem?

**Comment by peacemosquitto** [comment]
No unfortuantely not. My main requirement was to remotely change the frequency so I just wired the Fusion to the Pi's UART Tx and changed it that way. It would still be good to have a simple example of connecting a Pi to a Fusion that would allow bi directional comms. I tried adapting the wiring diagram on page 3 of the documentation but without success

**Comment by antoxi4** [comment]
> No unfortuantely not. My main requirement was to remotely change the frequency so I just wired the Fusion to the Pi's UART Tx and changed it that way. It would still be good to have a simple example of connecting a Pi to a Fusion that would allow bi directional comms. I tried adapting the wiring diagram on page 3 of the documentation but without success

Same stuff, i want to get some frequencies analysing data from tbs. but there is no any response.

**Comment by antoxi4** [comment]
> No unfortuantely not. My main requirement was to remotely change the frequency so I just wired the Fusion to the Pi's UART Tx and changed it that way. It would still be good to have a simple example of connecting a Pi to a Fusion that would allow bi directional comms. I tried adapting the wiring diagram on page 3 of the documentation but without success

Problem solved, i used schema for RS485 instead way on page 2/7. 
I just bought MAX485E and integrated it as it shows in schema on page 3/7.
but i remove from my scheme 120 Ohm resistor. And everything works fine, i can get response from TBS.

**Comment by wolpa29** [comment]
> > No unfortuantely not. My main requirement was to remotely change the frequency so I just wired the Fusion to the Pi's UART Tx and changed it that way. It would still be good to have a simple example of connecting a Pi to a Fusion that would allow bi directional comms. I tried adapting the wiring diagram on page 3 of the documentation but without success
> 
> Problem solved, i used schema for RS485 instead way on page 2/7. I just bought MAX485E and integrated it as it shows in schema on page 3/7. but i remove from my scheme 120 Ohm resistor. And everything works fine, i can get response from TBS.

Hey, i tried to make the sam ething but i get that error: 

Traceback (most recent call last):
  File "/home/paul/tbs_rs485_2.py", line 21, in <module>
    freq_received, rssi_a, rssi_b = fusion.get_frequency_rssi()
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/tbs_env/lib/python3.11/site-packages/tbsfusion/tbs_fusion.py", line 280, in get_frequency_rssi
    msg_data = self._receive_message(address,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/tbs_env/lib/python3.11/site-packages/tbsfusion/tbs_fusion.py", line 180, in _receive_message
    raise RuntimeError('No data received')
RuntimeError: No data received




Do you know what could be wrong?
I am using a RPI 3B with an Usb to RS485 converter and an RS485 Module which is connected to the TBS Fusion.
Would appreciate any help!!

**Comment by wolpa29** [comment]
The sent signal looks good, but do you know why there are these framing errors? And i get no response from the TBS. 
![image](https://github.com/user-attachments/assets/19fe8153-f693-4ccc-92eb-f1cecc7f0957)

I am using here the Frequenzi and RSSi request and the sent signal looks like that in the documentation. I am using 9600 baud

**Comment by antoxi4** [comment]
> > > No unfortuantely not. My main requirement was to remotely change the frequency so I just wired the Fusion to the Pi's UART Tx and changed it that way. It would still be good to have a simple example of connecting a Pi to a Fusion that would allow bi directional comms. I tried adapting the wiring diagram on page 3 of the documentation but without success
> > 
> > 
> > Problem solved, i used schema for RS485 instead way on page 2/7. I just bought MAX485E and integrated it as it shows in schema on page 3/7. but i remove from my scheme 120 Ohm resistor. And everything works fine, i can get response from TBS.
> 
> Hey, i tried to make the sam ething but i get that error:
> 
> Traceback (most recent call last): File "/home/paul/tbs_rs485_2.py", line 21, in freq_received, rssi_a, rssi_b = fusion.get_frequency_rssi() ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/paul/tbs_env/lib/python3.11/site-packages/tbsfusion/tbs_fusion.py", line 280, in get_frequency_rssi msg_data = self._receive_message(address, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/paul/tbs_env/lib/python3.11/site-packages/tbsfusion/tbs_fusion.py", line 180, in _receive_message raise RuntimeError('No data received') RuntimeError: No data received
> 
> Do you know what could be wrong? I am using a RPI 3B with an Usb to RS485 converter and an RS485 Module which is connected to the TBS Fusion. Would appreciate any help!!

Honestly if you bought just ready for use module it wasn't work in my case either, i made it using that chip https://imrad.com.ua/ru/max485esa-t

**Comment by sniperxnl** [comment]
@antoxi4 i have orderd the chip you tested, could you share the software you have made for this?

**Comment by antoxi4** [comment]
> [@antoxi4](https://github.com/antoxi4) i have orderd the chip you tested, could you share the software you have made for this?

Yeah, i made my own implementation, you can check it [here](https://github.com/antoxi4/node-tbs-fusion)

**Comment by sniperxnl** [comment]
Hi All, we try to get it working, when we use Max chips directly we can send and recieve, but when we place a optic fiber modul in between this is not working. 
Our plan is to use 4 fusion modules and control them from 1 place, but also get feedback.
This is the fiber modul we use
[https://primeda-telecom.store/products/1-analog-video-and-1-ttl-over-fiber-optic-up-20km-high-speed-sc-optical-transceiver-module-1310-1550nm-signal-converters-for-fpv-drone](url)

**Comment by sniperxnl** [comment]
@mluessi 
Could this work?
https://docs.google.com/document/d/1xUsm8MWRFkB3jvvvZi3-PKZsfzn0Rbwy0MkmNpx0CVw/edit?tab=t.0

**Comment by sniperxnl** [comment]
> <img alt="Screenshot 2024-05-09 at 2 35 44 PM" width="1427" src="https://private-user-images.githubusercontent.com/169354174/329230890-c2008338-b9f7-4945-9dac-87b86226d17f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTM0MzA5ODIsIm5iZiI6MTc1MzQzMDY4MiwicGF0aCI6Ii8xNjkzNTQxNzQvMzI5MjMwODkwLWMyMDA4MzM4LWI5ZjctNDk0NS05ZGFjLTg3Yjg2MjI2ZDE3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDcyNVQwODA0NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YTJiMzQ3OTZlMjhlNTJkZWJiMTZjOWRhZDI0N2Q3NDJkODBiYmI4Y2Q5YzM1ZTBhYWRmYTRlOWM1ZjU4NTllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lRTxGaNGeRkmGpPO0vqvAAxfXYIu7xN5BCKDlM4dPMA">

Did you get it working?
